version: 2

# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
  - A-dependency
  - I-dependency-gardening
  versioning-strategy: increase
  ignore:
  - dependency-name: typescript
    versions:
    - ">3.7"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 99
  labels:
  - A-dependency
  - I-dependency-gardening
