version: 2.1

###########################################
# Constants
###########################################
workspace_root: &workspace_root
    ~/repo

node_modules_dir: &node_modules_dir
    # XXX: should use glob?
    node_modules/

yarnpkg_cache_dir: &yarnpkg_cache_dir
    # We'd like to use the absolute path, but CircleCI command parser does not allow it.
    ./.cache/yarn


###########################################
# Executors Definitions
###########################################
executors:
    nodejs_10_executor:
        working_directory: *workspace_root
        docker:
            - image: node:10-buster
        environment:
            YARN_CACHE_FOLDER: *yarnpkg_cache_dir

    latest_nodejs_executor:
        working_directory: *workspace_root
        docker:
            - image: node:latest
        environment:
            YARN_CACHE_FOLDER: *yarnpkg_cache_dir


###########################################
# Commands Definitions
###########################################
commands:
    ###########################################
    # Bootstrap Commands
    ###########################################
    install_npm_dependency:
        description: "Install dependencies for Node.js"
        steps:
            - run:
                command: |
                    if [ -z "$YARN_CACHE_FOLDER" ]; then
                        echo '$YARN_CACHE_FOLDER  is undefined or empty string'
                        exit 1
                    fi
                    yarn install


###########################################
# Job Definitions
###########################################
jobs:
    minimum_build_and_test_for_every_change:
        executor: nodejs_10_executor
        steps:
            - checkout
            - install_npm_dependency
            - run: make ci -j 8

    latest_build_and_test_for_every_change:
        executor: latest_nodejs_executor
        steps:
            - checkout
            - install_npm_dependency
            - run: make ci -j 8


###########################################
# Workflow Conditions
###########################################
ignore_branches_for_bors: &ignore_branches_for_bors
    # These branches are used by bors-ng
    branches:
        ignore:
            - staging.tmp
            - trying.tmp


###########################################
# Workflow Definitions
###########################################
workflows:
    version: 2
    build_and_test:
        jobs:
            - minimum_build_and_test_for_every_change:
                filters:
                    <<: *ignore_branches_for_bors
            - latest_build_and_test_for_every_change:
                filters:
                    <<: *ignore_branches_for_bors
