version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - "A-dependency"
      - "I-dependency-gardening"
    ignored_updates:
      - match:
          dependency_name: "typescript"
          version_requirement: ">1.0"
    version_requirement_updates: "increase_versions"
