name: publish to npm
on:
    release:
        types: [created]
jobs:
    build:
        runs-on: ubuntu-latest
        container: node:15-buster

        steps:
            - uses: actions/checkout@v2
            - run: yarn install
            - run: make clean
            - run: make prepublish -j
            - run: make copy_npmrc_to_project_root
            - run: make publish -j
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
