name: publish to npm
on:
    release:
        types: [released]
jobs:
    build:
        runs-on: ubuntu-latest
        container: node:18-bullseye

        steps:
            - uses: actions/checkout@v3
            - run: yarn install
            - run: make clean
            - run: make prepublish -j
            - run: make publish -j
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
